name: stair_battle_counter
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  device_info_plus: ^9.0.1
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

assets:  


flutter:
  assets:
    - assets/svg/
  uses-material-design: true




